extend_labels = {
'EVENT:HURRICANE': ['EVENT:HURRICANE', 'STORM'],
'GPE': ['GPE', 'REGION'],
'CONTACT_INFO:url': ['CONTACT_INFO:url', 'COMMUNICATION'],
'CONTACT_INFO': ['CONTACT_INFO:url', 'COMMUNICATION'],
'GPE:STATE_PROVINCE': ['GPE:STATE_PROVINCE', 'REGION', 'STATE'],
'GPE:CITY': ['GPE:CITY', 'REGION'],
'GPE:COUNTRY': ['GPE:COUNTRY', 'REGION'],
'ORGANIZATION:EDUCATIONAL': ['ORGANIZATION:EDUCATIONAL', 'UNIVERSITY']
}
